// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("prismic")]
[assembly: AssemblyVersionAttribute("1.0.5")]
[assembly: AssemblyFileVersionAttribute("1.0.5")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.5";
    }
}
